#!/usr/bin/env python3
"""Interactive setup script for Aladdin MCP server OAuth configuration.

Guides the user step-by-step through creating the required environment
configuration with OAuth credentials for the Aladdin MCP server.
"""

from __future__ import annotations

import getpass
import os
import stat
import sys
from pathlib import Path


# ── Defaults ─────────────────────────────────────────────────────────────────

DEFAULT_CONFIG_DIR = Path.home() / ".aladdin"

FLOW_TYPES = {
    "1": ("refresh_token", "Refresh Token  — interactive / local development"),
    "2": ("client_credentials", "Client Credentials — app-to-app / service accounts"),
}

OUTPUT_FORMATS = {
    "1": "dotenv",
    "2": "shell",
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def _banner(text: str) -> None:
    width = max(len(text) + 4, 60)
    print()
    print("=" * width)
    print(f"  {text}")
    print("=" * width)
    print()


def _step(number: int, title: str) -> None:
    print(f"\n--- Step {number}: {title} ---\n")


def _prompt(label: str, *, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    prompt_text = f"  {label}{suffix}: "
    while True:
        value = getpass.getpass(prompt_text) if secret else input(prompt_text)
        value = value.strip() or default
        if value:
            return value
        print("    (required — please enter a value)")


def _choose(label: str, options: dict[str, tuple[str, str] | str]) -> str:
    print(f"  {label}")
    for key, val in options.items():
        display = val[1] if isinstance(val, tuple) else val
        print(f"    [{key}] {display}")
    while True:
        choice = input("  > ").strip()
        if choice in options:
            return choice
        print(f"    Invalid choice. Please enter one of: {', '.join(options)}")


def _confirm(message: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    answer = input(f"  {message} [{hint}]: ").strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def _escape_shell(value: str) -> str:
    """Escape a string for safe inclusion in a single-quoted shell variable."""
    return value.replace("'", "'\\''")


def _fmt_dotenv(key: str, value: str) -> str:
    return f"{key}={value}"


def _fmt_shell(key: str, value: str) -> str:
    return f"export {key}='{_escape_shell(value)}'"


# ── Config builder ───────────────────────────────────────────────────────────

def _build_config(
    *,
    fmt: str,
    username: str,
    auth_flow_type: str,
    client_id: str,
    client_secret: str,
    auth_server_url: str,
    refresh_token: str | None,
    access_token: str | None,
    default_web_server: str,
    configure_adc: bool,
    adc_access_token: str | None,
) -> str:
    line = _fmt_dotenv if fmt == "dotenv" else _fmt_shell
    header = "# Aladdin MCP server — generated by setup_oauth.py"
    if fmt == "shell":
        header += "\n# Source this file:  source <filename>"

    lines = [
        header,
        "",
        line("ASDK_USER_CREDENTIALS__USERNAME", username),
        line("defaultWebServer", default_web_server),
        "",
        line("ASDK_API__AUTH_TYPE", "OAuth"),
        line("ASDK_API__AUTH_FLOW_TYPE", auth_flow_type),
        line("ASDK_API__OAUTH__CLIENT_ID", client_id),
        line("ASDK_API__OAUTH__CLIENT_SECRET", client_secret),
        line("ASDK_API__OAUTH__AUTH_SERVER_URL", auth_server_url),
    ]

    if auth_flow_type == "refresh_token" and refresh_token:
        lines.append(line("ASDK_API__OAUTH__REFRESH_TOKEN", refresh_token))

    if access_token:
        lines.append(line("ASDK_API__OAUTH__ACCESS_TOKEN", access_token))

    if configure_adc:
        lines += ["", line("ASDK_ADC__CONN__AUTHENTICATOR", "oauth")]
        if adc_access_token:
            lines.append(line("ASDK_ADC__OAUTH__ACCESS_TOKEN", adc_access_token))

    lines.append("")
    return "\n".join(lines)


# ── Main flow ────────────────────────────────────────────────────────────────

def main() -> None:
    _banner("Aladdin MCP Server — OAuth Setup")

    print("This script will walk you through creating an OAuth configuration")
    print("for the Aladdin MCP server. You will need:")
    print()
    print("  - An OAuth application created in Aladdin Studio")
    print("  - Your Client ID and Client Secret")
    print("  - Your Auth Server URL")
    print("  - (Optional) A Refresh Token from your OAuth provider")
    print()
    if not _confirm("Ready to continue?"):
        print("\nSetup cancelled.")
        sys.exit(0)

    # ── Step 1: Output format ────────────────────────────────────────────────

    _step(1, "Choose output format")
    fmt_choice = _choose("How would you like to store the configuration?", {
        "1": ".env file (recommended — loaded automatically by the server)",
        "2": "Shell env file (source-able export script)",
    })
    output_format = OUTPUT_FORMATS[fmt_choice]

    # ── Step 2: User identity ────────────────────────────────────────────────

    _step(2, "User identity")
    username = _prompt("Aladdin username (e.g. jsmith)")
    default_web_server = _prompt(
        "Default web server (client environment URL)",
        default=os.getenv("defaultWebServer", ""),
    )

    # ── Step 3: OAuth flow type ──────────────────────────────────────────────

    _step(3, "OAuth flow type")
    flow_choice = _choose("Select the OAuth flow:", FLOW_TYPES)
    auth_flow_type = FLOW_TYPES[flow_choice][0]

    # ── Step 4: Client credentials ───────────────────────────────────────────

    _step(4, "Client credentials")
    print("  These come from your OAuth application in Aladdin Studio.\n")
    client_id = _prompt("Client ID")
    client_secret = _prompt("Client Secret", secret=True)
    auth_server_url = _prompt("Auth Server URL (e.g. https://host/oauth2/token)")

    # ── Step 5: Tokens ───────────────────────────────────────────────────────

    _step(5, "Tokens")
    refresh_token: str | None = None
    access_token: str | None = None

    if auth_flow_type == "refresh_token":
        print("  If you already have a refresh token, enter it now.")
        print("  Otherwise, generate one via your OAuth provider after setup.\n")
        refresh_token = _prompt("Refresh Token (or press Enter to skip)", default="PLACEHOLDER") or None
        if refresh_token == "PLACEHOLDER":
            refresh_token = None
            print("\n  [!] You will need to generate a refresh token before using the server.")
            print("      Use your OAuth provider's authorization flow to obtain one.")
    else:
        print("  Client-credentials flow does not require a refresh token.\n")

    if _confirm("Do you have a pre-generated access token to provide?", default=False):
        access_token = _prompt("Access Token", secret=True)

    # ── Step 6: ADC (Snowflake) ──────────────────────────────────────────────

    _step(6, "ADC / Snowflake OAuth (optional)")
    configure_adc = _confirm("Configure ADC (Snowflake) OAuth?", default=False)
    adc_access_token: str | None = None
    if configure_adc:
        if _confirm("Provide a separate ADC access token? (No = reuse API token)", default=False):
            adc_access_token = _prompt("ADC Access Token", secret=True)

    # ── Step 7: Write config ─────────────────────────────────────────────────

    _step(7, "Save configuration")

    build_args = dict(
        username=username,
        auth_flow_type=auth_flow_type,
        client_id=client_id,
        client_secret=client_secret,
        auth_server_url=auth_server_url,
        refresh_token=refresh_token,
        access_token=access_token,
        default_web_server=default_web_server,
        configure_adc=configure_adc,
        adc_access_token=adc_access_token,
    )

    content = _build_config(fmt=output_format, **build_args)
    if output_format == "dotenv":
        default_path = str(DEFAULT_CONFIG_DIR / ".env")
    else:
        default_path = str(DEFAULT_CONFIG_DIR / "aladdin_env.sh")

    out_path_str = _prompt("Output file path", default=default_path)
    out_path = Path(out_path_str).expanduser().resolve()

    # Preview
    print("\n  --- Preview ---")
    # Redact secrets in the preview
    preview = content
    for secret_val in filter(None, [client_secret, refresh_token, access_token, adc_access_token]):
        if len(secret_val) > 8:
            redacted = secret_val[:4] + "****" + secret_val[-4:]
        else:
            redacted = "****"
        preview = preview.replace(secret_val, redacted)
    for line in preview.splitlines():
        print(f"  | {line}")
    print("  --- End preview ---\n")

    if not _confirm(f"Write to {out_path}?"):
        print("\n  Setup cancelled. Nothing was written.")
        sys.exit(0)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8-sig")
    # Restrict file permissions to owner-only (secrets inside)
    out_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600

    print(f"\n  Config written to: {out_path}")
    print(f"  File permissions set to 600 (owner read/write only).")

    # ── Step 8: Next steps ───────────────────────────────────────────────────

    _step(8, "Next steps")

    if output_format == "dotenv":
        print(f"  1. Place the .env file where the server runs, or set:")
        print(f"     export DOTENV_PATH=\"{out_path}\"\n")
        print(f"     Or copy it to your project directory as '.env'.\n")
    else:
        print(f"  1. Source the env file:")
        print(f"     source \"{out_path}\"\n")
        print(f"     Add this to your shell profile (~/.bashrc, ~/.zshrc) to persist it.\n")

    if auth_flow_type == "refresh_token" and not refresh_token:
        print("  2. Generate a refresh token via your OAuth provider's")
        print("     authorization flow, then update your config with it.\n")

    print("  You can now start the Aladdin MCP server:")
    print("     aladdin-mcp")
    print()
    print("  Done!")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n  Setup interrupted. Nothing was written.")
        sys.exit(1)
